apiVersion: apps/v1
kind: Deployment
metadata:
  name: <appname>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <appname>
  template:
    metadata:
      labels:
        app: <appname>
    spec:
      containers:
      - name: <appname>
        image: <acrname>.azurecr.io/app/<appname>:v1 # image in ACR
        resources: {}# include resources for better scheduling
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: <appname>
spec:
  ports:
  - port: 80 # Access on service port 80
    protocol: TCP
    targetPort: 80
  selector:
    app: <appname>
  type: LoadBalancer # External Access via load balancer service
